#define __LAMPHEADER_NULL ((void*)0)
#define __LAMPHEADER_TREGION_SIZE (0x4000)
#define __LAMPHEADER_PREGION_SIZE (0xC000)

#define __LAMPHEADER_DECLAREF(a) __LAMPHEADER_CLOSURE* a(__LAMPHEADER_CLOSURE* __LAMPHEADER_this, __LAMPHEADER_CLOSURE* __LAMPHEADER_arg);
#define __LAMPHEADER_DEFINEF0(a, b)\
__LAMPHEADER_CLOSURE* a(__LAMPHEADER_CLOSURE* __LAMPHEADER_this, __LAMPHEADER_CLOSURE* __LAMPHEADER_arg) {\
    __LAMPHEADER_ENVIRONMENT* __LAMPHEADER_nenv = __LAMPHEADER_extenv(__LAMPHEADER_this->data.env, __LAMPHEADER_arg);\
    return __LAMPHEADER_ccreat(b, (long)__LAMPHEADER_nenv, 0);\
}
#define __LAMPHEADER_DEFINEF1(a, b)\
__LAMPHEADER_CLOSURE* a(__LAMPHEADER_CLOSURE* __LAMPHEADER_this, __LAMPHEADER_CLOSURE* __LAMPHEADER_arg) {\
    __LAMPHEADER_ENVIRONMENT* __LAMPHEADER_nenv = __LAMPHEADER_extenv(__LAMPHEADER_this->data.env, __LAMPHEADER_arg);\
    b\
}
#define __LAMPHEADER_DEFINEV(a, b) __LAMPHEADER_CLOSURE* a = b;
#define __LAMPHEADER_CCREAT(a, b, c) __LAMPHEADER_ccreat(a, (long)b, c)
#define __LAMPHEADER_APPLY(a, b) __LAMPHEADER_apply(a, b)
#define __LAMPHEADER_LOOKUP(a) __LAMPHEADER_lookup(__LAMPHEADER_nenv, a)
#define __LAMPHEADER_RETURN(a) return a;
#define __LAMPHEADER_ARGC __LAMPHEADER_WRAP(argc)
#define __LAMPHEADER_ARGV(a) __LAMPHEADER_WRAP(argv[__LAMPHEADER_UNWRAP(a)])
#define __LAMPHEADER_READSIZE1(a) *(char*)a
#define __LAMPHEADER_READSIZE2(a) *(short*)a
#define __LAMPHEADER_READSIZE4(a) *(int*)a
#define __LAMPHEADER_READSIZE8(a) *(long*)a
#define __LAMPHEADER_WRITESIZE1(a, b) *(char*)a = b
#define __LAMPHEADER_WRITESIZE2(a, b) *(short*)a = b
#define __LAMPHEADER_WRITESIZE4(a, b) *(int*)a = b
#define __LAMPHEADER_WRITESIZE8(a, b) *(long*)a = b
#define __LAMPHEADER_WRAPPER(a) int main(int argc, char** argv) {__LAMPHEADER_ENVIRONMENT* __LAMPHEADER_nenv = __LAMPHEADER_NULL; a;}
#define __LAMPHEADER_DECLAREXT(a, b) extern long a b;
#define __LAMPHEADER_EXTCALL(a, b) a b
#define __LAMPHEADER_DEFINES(a, b) char a[b] = {0, };
#define __LAMPHEADER_GETS(a) __LAMPHEADER_WRAP((long)&a[0])
#define __LAMPHEADER_DEFINEC(a, b) __LAMPHEADER_CLOSURE* a = __LAMPHEADER_COPY(b);
#define __LAMPHEADER_CHURCH(a) __LAMPHEADER_church_to_native(a)
#define __LAMPHEADER_IFTHENELSE(a, b, c) (a ? b : c)
#define __LAMPHEADER_CHECKTF(a) __LAMPHEADER_check_tf(a)
#define __LAMPHEADER_CHECKERR __LAMPHEADER_CLEAR;if(__LAMPHEADER_iserr){return -1;}
#define __LAMPHEADER_WRAP(a) __LAMPHEADER_CCREAT(__LAMPHEADER_NULL, a, 1)
#define __LAMPHEADER_UNWRAP(a) a->data.n
#define __LAMPHEADER_COPY(a) __LAMPHEADER_move_region(a)
#define __LAMPHEADER_CLEAR __LAMPHEADER_freal()


typedef struct __LAMPHEADER__CLOSURE {
    struct __LAMPHEADER__CLOSURE* (*fn)(struct __LAMPHEADER__CLOSURE*, struct __LAMPHEADER__CLOSURE*);
    union {
        struct __LAMPHEADER__ENVIRONMENT* env;
        long n;
    } data;
    char isint;
} __LAMPHEADER_CLOSURE;
typedef struct __LAMPHEADER__ENVIRONMENT {
    struct __LAMPHEADER__CLOSURE* value;
    struct __LAMPHEADER__ENVIRONMENT* next;
} __LAMPHEADER_ENVIRONMENT;

char __LAMPHEADER_tregion[__LAMPHEADER_TREGION_SIZE] = {0, };
char __LAMPHEADER_pregion[__LAMPHEADER_PREGION_SIZE] = {0, };
unsigned int __LAMPHEADER_trptr = 0;
unsigned int __LAMPHEADER_prptr = 0;
char __LAMPHEADER_iserr = 0;

void __LAMPHEADER_memcpy(void* __LAMPHEADER_s1, void* __LAMPHEADER_s2, long __LAMPHEADER_n) {
    for (long __LAMPHEADER_i = 0; __LAMPHEADER_i < __LAMPHEADER_n; __LAMPHEADER_i++) {
        ((char*)__LAMPHEADER_s1)[__LAMPHEADER_i] = ((char*)__LAMPHEADER_s2)[__LAMPHEADER_i];
    }
}
void __LAMPHEADER_memset(void* __LAMPHEADER_s, char __LAMPHEADER_c, long __LAMPHEADER_n) {
    for (long __LAMPHEADER_i = 0; __LAMPHEADER_i < __LAMPHEADER_n; __LAMPHEADER_i++) {
        ((char*)__LAMPHEADER_s)[__LAMPHEADER_i] = __LAMPHEADER_c;
    }
}
void* __LAMPHEADER_malloc(long __LAMPHEADER_size) {
    unsigned int __LAMPHEADER_ret = __LAMPHEADER_trptr;
    __LAMPHEADER_trptr += __LAMPHEADER_size;
    return &__LAMPHEADER_tregion[__LAMPHEADER_ret];
}
void __LAMPHEADER_freal() {
    __LAMPHEADER_memset(__LAMPHEADER_tregion, 0, __LAMPHEADER_TREGION_SIZE);
    __LAMPHEADER_trptr = 0;
}
void __LAMPHEADER_traverse(__LAMPHEADER_ENVIRONMENT*);
__LAMPHEADER_CLOSURE* __LAMPHEADER_move_region(__LAMPHEADER_CLOSURE* __LAMPHEADER_c) {
    if (!__LAMPHEADER_c->isint) {
        __LAMPHEADER_traverse(__LAMPHEADER_c->data.env);
    }
    void* __LAMPHEADER_target = &__LAMPHEADER_pregion[__LAMPHEADER_prptr];
    __LAMPHEADER_memcpy(__LAMPHEADER_target, __LAMPHEADER_c, sizeof(__LAMPHEADER_CLOSURE));
    __LAMPHEADER_prptr += sizeof(__LAMPHEADER_CLOSURE);
    return __LAMPHEADER_target;
}
void __LAMPHEADER_traverse(__LAMPHEADER_ENVIRONMENT* __LAMPHEADER_env) {
    if (__LAMPHEADER_env == __LAMPHEADER_NULL) {
        return;
    }
    __LAMPHEADER_env->value = __LAMPHEADER_move_region(__LAMPHEADER_env->value);
    void* __LAMPHEADER_target = &__LAMPHEADER_pregion[__LAMPHEADER_prptr];
    __LAMPHEADER_memcpy(__LAMPHEADER_target, __LAMPHEADER_env, sizeof(__LAMPHEADER_ENVIRONMENT));
    __LAMPHEADER_prptr += sizeof(__LAMPHEADER_ENVIRONMENT);
    __LAMPHEADER_env = __LAMPHEADER_target;
}
__LAMPHEADER_ENVIRONMENT* __LAMPHEADER_extenv(__LAMPHEADER_ENVIRONMENT* __LAMPHEADER_env, __LAMPHEADER_CLOSURE* __LAMPHEADER_args) {
    if (__LAMPHEADER_env == __LAMPHEADER_NULL) {
        __LAMPHEADER_env = __LAMPHEADER_malloc(sizeof(__LAMPHEADER_ENVIRONMENT));
        __LAMPHEADER_env->next = __LAMPHEADER_NULL;
        __LAMPHEADER_env->value = __LAMPHEADER_args;
        return __LAMPHEADER_env;
    }
    __LAMPHEADER_ENVIRONMENT* __LAMPHEADER_nenv = __LAMPHEADER_malloc(sizeof(__LAMPHEADER_ENVIRONMENT));
    __LAMPHEADER_nenv->value = __LAMPHEADER_args;
    __LAMPHEADER_nenv->next = __LAMPHEADER_env;
    return __LAMPHEADER_nenv;
}
__LAMPHEADER_CLOSURE* __LAMPHEADER_self(__LAMPHEADER_CLOSURE* __LAMPHEADER_this, __LAMPHEADER_CLOSURE* __LAMPHEADER_arg) {
    return __LAMPHEADER_this;
}
__LAMPHEADER_CLOSURE* __LAMPHEADER_ccreat(__LAMPHEADER_CLOSURE* (*__LAMPHEADER_c)(__LAMPHEADER_CLOSURE*, __LAMPHEADER_CLOSURE*), long __LAMPHEADER_data, char __LAMPHEADER_isint) {
    __LAMPHEADER_CLOSURE* __LAMPHEADER_ret = __LAMPHEADER_malloc(sizeof(__LAMPHEADER_CLOSURE));
    __LAMPHEADER_ret->fn = __LAMPHEADER_c;
    __LAMPHEADER_ret->isint = __LAMPHEADER_isint;
    if (__LAMPHEADER_isint) {
        __LAMPHEADER_ret->data.n = (long)__LAMPHEADER_data;
        return __LAMPHEADER_ret;
    }
    __LAMPHEADER_ret->data.env = (__LAMPHEADER_ENVIRONMENT*)__LAMPHEADER_data;
    return __LAMPHEADER_ret;
}
__LAMPHEADER_CLOSURE* __LAMPHEADER_apply(__LAMPHEADER_CLOSURE* __LAMPHEADER_arg0, __LAMPHEADER_CLOSURE* __LAMPHEADER_arg1) {
    if (__LAMPHEADER_arg0->isint && !__LAMPHEADER_arg1->isint) {
        __LAMPHEADER_iserr = 1;
        __LAMPHEADER_CLOSURE* __LAMPHEADER_ret = __LAMPHEADER_ccreat(__LAMPHEADER_self, (long)__LAMPHEADER_NULL, 0);
        return __LAMPHEADER_ret->fn(__LAMPHEADER_ret, __LAMPHEADER_arg1);
    }
    return __LAMPHEADER_arg0->fn(__LAMPHEADER_arg0, __LAMPHEADER_arg1);
}
__LAMPHEADER_CLOSURE* __LAMPHEADER_lookup(__LAMPHEADER_ENVIRONMENT* __LAMPHEADER_env, unsigned long __LAMPHEADER_depth) {
    if (__LAMPHEADER_depth > 0) {
        return __LAMPHEADER_lookup(__LAMPHEADER_env->next, __LAMPHEADER_depth - 1);
    }
    return __LAMPHEADER_env->value;
}
__LAMPHEADER_CLOSURE* __LAMPHEADER_church(__LAMPHEADER_CLOSURE* __LAMPHEADER_this, __LAMPHEADER_CLOSURE* __LAMPHEADER_arg) {
    (__LAMPHEADER_this->data.n)++;
    return __LAMPHEADER_this;
}
__LAMPHEADER_CLOSURE* __LAMPHEADER_church_to_native(__LAMPHEADER_CLOSURE* __LAMPHEADER_num) {
    if (__LAMPHEADER_num->isint) {
        return __LAMPHEADER_num;
    }
    
    unsigned int __LAMPHEADER_init = __LAMPHEADER_trptr;
    __LAMPHEADER_CLOSURE* __LAMPHEADER_counter = __LAMPHEADER_ccreat(__LAMPHEADER_church, 0, 0);
    __LAMPHEADER_CLOSURE* __LAMPHEADER_dummy = __LAMPHEADER_ccreat(__LAMPHEADER_self, (long)__LAMPHEADER_NULL, 0);
    long __LAMPHEADER_ret = __LAMPHEADER_APPLY(__LAMPHEADER_APPLY(__LAMPHEADER_num, __LAMPHEADER_counter), __LAMPHEADER_dummy)->data.n;
    __LAMPHEADER_trptr = __LAMPHEADER_init;
    return __LAMPHEADER_CCREAT(__LAMPHEADER_NULL, __LAMPHEADER_ret, 1);
}
char __LAMPHEADER_check_tf(__LAMPHEADER_CLOSURE* __LAMPHEADER_cond) {
    if (__LAMPHEADER_cond->isint) {
        return __LAMPHEADER_cond->data.n;
    }

    unsigned int __LAMPHEADER_init = __LAMPHEADER_trptr;
    __LAMPHEADER_CLOSURE* __LAMPHEADER_ctrue = __LAMPHEADER_ccreat(__LAMPHEADER_self, 1, 0);
    __LAMPHEADER_CLOSURE* __LAMPHEADER_cfalse = __LAMPHEADER_ccreat(__LAMPHEADER_self, 0, 0);
    char __LAMPHEADER_ret = (char)__LAMPHEADER_APPLY(__LAMPHEADER_APPLY(__LAMPHEADER_cond, __LAMPHEADER_ctrue), __LAMPHEADER_cfalse)->data.n;
    __LAMPHEADER_trptr = __LAMPHEADER_init;
    if (__LAMPHEADER_ret != 0 && __LAMPHEADER_ret != 1) {
        __LAMPHEADER_iserr = 1;
        return -1;
    }
    else return __LAMPHEADER_ret;
}
__LAMPHEADER_CLOSURE* __LAMPHEADER_add1(__LAMPHEADER_CLOSURE* __LAMPHEADER_this, __LAMPHEADER_CLOSURE* __LAMPHEADER_arg) {
    __LAMPHEADER_UNWRAP(__LAMPHEADER_this) += __LAMPHEADER_UNWRAP(__LAMPHEADER_arg);
    return __LAMPHEADER_this;
}
__LAMPHEADER_CLOSURE* __LAMPHEADER_add0(__LAMPHEADER_CLOSURE* __LAMPHEADER_this, __LAMPHEADER_CLOSURE* __LAMPHEADER_arg) {
    return __LAMPHEADER_CCREAT(__LAMPHEADER_add1, __LAMPHEADER_UNWRAP(__LAMPHEADER_arg), 1);
}
__LAMPHEADER_CLOSURE* __LAMPHEADER_sub1(__LAMPHEADER_CLOSURE* __LAMPHEADER_this, __LAMPHEADER_CLOSURE* __LAMPHEADER_arg) {
    __LAMPHEADER_UNWRAP(__LAMPHEADER_this) -= __LAMPHEADER_UNWRAP(__LAMPHEADER_arg);
    return __LAMPHEADER_this;
}
__LAMPHEADER_CLOSURE* __LAMPHEADER_sub0(__LAMPHEADER_CLOSURE* __LAMPHEADER_this, __LAMPHEADER_CLOSURE* __LAMPHEADER_arg) {
    return __LAMPHEADER_CCREAT(__LAMPHEADER_sub1, __LAMPHEADER_UNWRAP(__LAMPHEADER_arg), 1);
}
__LAMPHEADER_CLOSURE* __LAMPHEADER_mul1(__LAMPHEADER_CLOSURE* __LAMPHEADER_this, __LAMPHEADER_CLOSURE* __LAMPHEADER_arg) {
    __LAMPHEADER_UNWRAP(__LAMPHEADER_this) *= __LAMPHEADER_UNWRAP(__LAMPHEADER_arg);
    return __LAMPHEADER_this;
}
__LAMPHEADER_CLOSURE* __LAMPHEADER_mul0(__LAMPHEADER_CLOSURE* __LAMPHEADER_this, __LAMPHEADER_CLOSURE* __LAMPHEADER_arg) {
    return __LAMPHEADER_CCREAT(__LAMPHEADER_mul1, __LAMPHEADER_UNWRAP(__LAMPHEADER_arg), 1);
}
__LAMPHEADER_CLOSURE* __LAMPHEADER_div1(__LAMPHEADER_CLOSURE* __LAMPHEADER_this, __LAMPHEADER_CLOSURE* __LAMPHEADER_arg) {
    __LAMPHEADER_UNWRAP(__LAMPHEADER_this) /= __LAMPHEADER_UNWRAP(__LAMPHEADER_arg);
    return __LAMPHEADER_this;
}
__LAMPHEADER_CLOSURE* __LAMPHEADER_div0(__LAMPHEADER_CLOSURE* __LAMPHEADER_this, __LAMPHEADER_CLOSURE* __LAMPHEADER_arg) {
    return __LAMPHEADER_CCREAT(__LAMPHEADER_div1, __LAMPHEADER_UNWRAP(__LAMPHEADER_arg), 1);
}
__LAMPHEADER_CLOSURE* __LAMPHEADER_mod1(__LAMPHEADER_CLOSURE* __LAMPHEADER_this, __LAMPHEADER_CLOSURE* __LAMPHEADER_arg) {
    __LAMPHEADER_UNWRAP(__LAMPHEADER_this) %= __LAMPHEADER_UNWRAP(__LAMPHEADER_arg);
    return __LAMPHEADER_this;
}
__LAMPHEADER_CLOSURE* __LAMPHEADER_mod0(__LAMPHEADER_CLOSURE* __LAMPHEADER_this, __LAMPHEADER_CLOSURE* __LAMPHEADER_arg) {
    return __LAMPHEADER_CCREAT(__LAMPHEADER_mod1, __LAMPHEADER_UNWRAP(__LAMPHEADER_arg), 1);
}
__LAMPHEADER_CLOSURE* __LAMPHEADER_read1(__LAMPHEADER_CLOSURE* __LAMPHEADER_this, __LAMPHEADER_CLOSURE* __LAMPHEADER_arg) {
    __LAMPHEADER_ENVIRONMENT* __LAMPHEADER_nenv = __LAMPHEADER_extenv(__LAMPHEADER_this->data.env, __LAMPHEADER_arg);
    long __LAMPHEADER_v0 = __LAMPHEADER_UNWRAP(__LAMPHEADER_LOOKUP(0));
    long __LAMPHEADER_v1 = __LAMPHEADER_UNWRAP(__LAMPHEADER_LOOKUP(1));
    long __LAMPHEADER_ret = 0;
    switch (__LAMPHEADER_v0) {
        case 1: __LAMPHEADER_ret = __LAMPHEADER_READSIZE1(__LAMPHEADER_v1); break;
        case 2: __LAMPHEADER_ret = __LAMPHEADER_READSIZE2(__LAMPHEADER_v1); break;
        case 4: __LAMPHEADER_ret = __LAMPHEADER_READSIZE4(__LAMPHEADER_v1); break;
        case 8: __LAMPHEADER_ret = __LAMPHEADER_READSIZE8(__LAMPHEADER_v1); break;
        default: {
            __LAMPHEADER_iserr = 1;
            __LAMPHEADER_ret = -1;
        }
    }
    return __LAMPHEADER_WRAP(__LAMPHEADER_ret);
}
__LAMPHEADER_CLOSURE* __LAMPHEADER_read0(__LAMPHEADER_CLOSURE* __LAMPHEADER_this, __LAMPHEADER_CLOSURE* __LAMPHEADER_arg) {
    __LAMPHEADER_ENVIRONMENT* __LAMPHEADER_nenv = __LAMPHEADER_extenv(__LAMPHEADER_this->data.env, __LAMPHEADER_arg);
    return __LAMPHEADER_CCREAT(__LAMPHEADER_read1, __LAMPHEADER_nenv, 0);
}
__LAMPHEADER_CLOSURE* __LAMPHEADER_write2(__LAMPHEADER_CLOSURE* __LAMPHEADER_this, __LAMPHEADER_CLOSURE* __LAMPHEADER_arg) {
    __LAMPHEADER_ENVIRONMENT* __LAMPHEADER_nenv = __LAMPHEADER_extenv(__LAMPHEADER_this->data.env, __LAMPHEADER_arg);
    long __LAMPHEADER_v0 = __LAMPHEADER_UNWRAP(__LAMPHEADER_LOOKUP(0));
    long __LAMPHEADER_v1 = __LAMPHEADER_UNWRAP(__LAMPHEADER_LOOKUP(1));
    long __LAMPHEADER_v2 = __LAMPHEADER_UNWRAP(__LAMPHEADER_LOOKUP(2));
    long __LAMPHEADER_ret = 0;
    switch (__LAMPHEADER_v0) {
        case 1: __LAMPHEADER_WRITESIZE1(__LAMPHEADER_v2, __LAMPHEADER_v1); break;
        case 2: __LAMPHEADER_WRITESIZE2(__LAMPHEADER_v2, __LAMPHEADER_v1); break;
        case 4: __LAMPHEADER_WRITESIZE4(__LAMPHEADER_v2, __LAMPHEADER_v1); break;
        case 8: __LAMPHEADER_WRITESIZE8(__LAMPHEADER_v2, __LAMPHEADER_v1); break;
        default: {
            __LAMPHEADER_iserr = 1;
            __LAMPHEADER_ret = -1;
        }
    }
    return __LAMPHEADER_WRAP(__LAMPHEADER_ret);
}
__LAMPHEADER_CLOSURE* __LAMPHEADER_write1(__LAMPHEADER_CLOSURE* __LAMPHEADER_this, __LAMPHEADER_CLOSURE* __LAMPHEADER_arg) {
    __LAMPHEADER_ENVIRONMENT* __LAMPHEADER_nenv = __LAMPHEADER_extenv(__LAMPHEADER_this->data.env, __LAMPHEADER_arg);
    return __LAMPHEADER_CCREAT(__LAMPHEADER_write2, __LAMPHEADER_nenv, 0);
}
__LAMPHEADER_CLOSURE* __LAMPHEADER_write0(__LAMPHEADER_CLOSURE* __LAMPHEADER_this, __LAMPHEADER_CLOSURE* __LAMPHEADER_arg) {
    __LAMPHEADER_ENVIRONMENT* __LAMPHEADER_nenv = __LAMPHEADER_extenv(__LAMPHEADER_this->data.env, __LAMPHEADER_arg);
    return __LAMPHEADER_CCREAT(__LAMPHEADER_write1, __LAMPHEADER_nenv, 0);
}