#include <stdio.h>

#define __LAMPHEADERDATA_NULL ((void*)0)
#define __LAMPHEADERDATA_REGION_SIZE (0x4000)

#define __LAMPHEADERDATA_DECLAREF(a) __LAMPHEADERDATA_CLOSURE* a(__LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_this, __LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_arg);
#define __LAMPHEADERDATA_DEFINEF0(a, b)\
__LAMPHEADERDATA_CLOSURE* a(__LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_this, __LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_arg) {\
    __LAMPHEADERDATA_ENVIRONMENT* __LAMPHEADERDATA_nenv = __LAMPHEADERDATA_extenv(__LAMPHEADERDATA_this->env, __LAMPHEADERDATA_arg);\
    return __LAMPHEADERDATA_ccreat(b, __LAMPHEADERDATA_nenv);\
}
#define __LAMPHEADERDATA_DEFINEF1(a, b)\
__LAMPHEADERDATA_CLOSURE* a(__LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_this, __LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_arg) {\
    __LAMPHEADERDATA_ENVIRONMENT* __LAMPHEADERDATA_nenv = __LAMPHEADERDATA_extenv(__LAMPHEADERDATA_this->env, __LAMPHEADERDATA_arg);\
    b\
}
#define __LAMPHEADERDATA_DEFINEV(a, b) __LAMPHEADERDATA_CLOSURE* a = b;
#define __LAMPHEADERDATA_CCREAT(a, b) __LAMPHEADERDATA_ccreat(a, b)
#define __LAMPHEADERDATA_APPLY(a, b) __LAMPHEADERDATA_apply(a, b)
#define __LAMPHEADERDATA_LOOKUP(a) __LAMPHEADERDATA_lookup(__LAMPHEADERDATA_nenv, a)
#define __LAMPHEADERDATA_RETURN(a) return a;
#define __LAMPHEADERDATA_ARGC argc
#define __LAMPHEADERDATA_ARGV(a) argv[a]
#define __LAMPHEADERDATA_SIZE1 volatile unsigned char
#define __LAMPHEADERDATA_SIZE2 volatile unsigned short int
#define __LAMPHEADERDATA_SIZE4 volatile unsigned int
#define __LAMPHEADERDATA_SIZE8 volatile unsigned long int
#define __LAMPHEADERDATA_READSIZE1(a) *(__LAMPHEADERDATA_SIZE1 *)a
#define __LAMPHEADERDATA_READSIZE2(a) *(__LAMPHEADERDATA_SIZE2 *)a
#define __LAMPHEADERDATA_READSIZE4(a) *(__LAMPHEADERDATA_SIZE4 *)a
#define __LAMPHEADERDATA_READSIZE8(a) *(__LAMPHEADERDATA_SIZE8 *)a
#define __LAMPHEADERDATA_WRITESIZE1(a, b) *(__LAMPHEADERDATA_SIZE1 *)a = b
#define __LAMPHEADERDATA_WRITESIZE2(a, b) *(__LAMPHEADERDATA_SIZE2 *)a = b
#define __LAMPHEADERDATA_WRITESIZE4(a, b) *(__LAMPHEADERDATA_SIZE4 *)a = b
#define __LAMPHEADERDATA_WRITESIZE8(a, b) *(__LAMPHEADERDATA_SIZE8 *)a = b
#define __LAMPHEADERDATA_WRAPPER(a) int main(int argc, char** argv) {__LAMPHEADERDATA_ENVIRONMENT* __LAMPHEADERDATA_nenv = __LAMPHEADERDATA_NULL; a; printf("rptr %d\n", __LAMPHEADERDATA_rptr);}
#define __LAMPHEADERDATA_DECLAREXT(a, b) extern unsigned long int a b;
#define __LAMPHEADERDATA_EXTCALL(a, b) a b
#define __LAMPHEADERDATA_DEFINES(a, b) unsigned char a[b] = {0, };
#define __LAMPHEADERDATA_GETS(a) &a[0]
#define __LAMPHEADERDATA_DEFINEC(a, b) unsigned long int a = (unsigned long int)b;
#define __LAMPHEADERDATA_DECODE(a) __LAMPHEADERDATA_decode_church((__LAMPHEADERDATA_CLOSURE*)a)
#define __LAMPHEADERDATA_IFTHENELSE(a, b, c) (a ? b : c)
#define __LAMPHEADERDATA_CHECKTF(a) __LAMPHEADERDATA_check_tf(a)


typedef struct __LAMPHEADERDATA__CLOSURE {
    struct __LAMPHEADERDATA__CLOSURE* (*fn)(struct __LAMPHEADERDATA__CLOSURE*, struct __LAMPHEADERDATA__CLOSURE*);
    struct __LAMPHEADERDATA__ENVIRONMENT* env;
} __LAMPHEADERDATA_CLOSURE;
typedef struct __LAMPHEADERDATA__ENVIRONMENT {
    struct __LAMPHEADERDATA__CLOSURE* value;
    struct __LAMPHEADERDATA__ENVIRONMENT* next;
} __LAMPHEADERDATA_ENVIRONMENT;

unsigned char __LAMPHEADERDATA_region[__LAMPHEADERDATA_REGION_SIZE] = {0, };
unsigned int __LAMPHEADERDATA_rptr = 0;
__LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_tmp = __LAMPHEADERDATA_NULL;

void __LAMPHEADERDATA_memcpy(void* __LAMPHEADERDATA_s1, void* __LAMPHEADERDATA_s2, unsigned long int __LAMPHEADERDATA_n) {
    for (unsigned long int __LAMPHEADERDATA_i = 0; __LAMPHEADERDATA_i < __LAMPHEADERDATA_n; __LAMPHEADERDATA_i++) {
        ((char*)__LAMPHEADERDATA_s1)[__LAMPHEADERDATA_i] = ((char*)__LAMPHEADERDATA_s2)[__LAMPHEADERDATA_i];
    }
}
void __LAMPHEADERDATA_memset(void* __LAMPHEADERDATA_s, char __LAMPHEADERDATA_c, unsigned long int __LAMPHEADERDATA_n) {
    for (unsigned long int __LAMPHEADERDATA_i = 0; __LAMPHEADERDATA_i < __LAMPHEADERDATA_n; __LAMPHEADERDATA_i++) {
        ((char*)__LAMPHEADERDATA_s)[__LAMPHEADERDATA_i] = __LAMPHEADERDATA_c;
    }
}
void* __LAMPHEADERDATA_malloc(unsigned long int __LAMPHEADERDATA_size) {
    unsigned int __LAMPHEADERDATA_ret = __LAMPHEADERDATA_rptr;
    __LAMPHEADERDATA_rptr += __LAMPHEADERDATA_size;
    return &__LAMPHEADERDATA_region[__LAMPHEADERDATA_ret];
}
void __LAMPHEADERDATA_freal() {
    __LAMPHEADERDATA_memset(__LAMPHEADERDATA_region, 0, __LAMPHEADERDATA_REGION_SIZE);
    __LAMPHEADERDATA_rptr = 0;
}
__LAMPHEADERDATA_ENVIRONMENT* __LAMPHEADERDATA_extenv(__LAMPHEADERDATA_ENVIRONMENT* __LAMPHEADERDATA_env, __LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_args) {
    if (__LAMPHEADERDATA_env == __LAMPHEADERDATA_NULL) {
        __LAMPHEADERDATA_env = __LAMPHEADERDATA_malloc(sizeof(__LAMPHEADERDATA_ENVIRONMENT));
        __LAMPHEADERDATA_env->next = __LAMPHEADERDATA_NULL;
        __LAMPHEADERDATA_env->value = __LAMPHEADERDATA_args;
        return __LAMPHEADERDATA_env;
    }
    else {
        __LAMPHEADERDATA_ENVIRONMENT* __LAMPHEADERDATA_nenv = __LAMPHEADERDATA_malloc(sizeof(__LAMPHEADERDATA_ENVIRONMENT));
        __LAMPHEADERDATA_nenv->value = __LAMPHEADERDATA_args;
        __LAMPHEADERDATA_nenv->next = __LAMPHEADERDATA_env;
        return __LAMPHEADERDATA_nenv;
    }
}
__LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_ccreat(__LAMPHEADERDATA_CLOSURE* (*__LAMPHEADERDATA_c)(__LAMPHEADERDATA_CLOSURE*, __LAMPHEADERDATA_CLOSURE*), __LAMPHEADERDATA_ENVIRONMENT* __LAMPHEADERDATA_nenv) {
    __LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_ret = __LAMPHEADERDATA_malloc(sizeof(__LAMPHEADERDATA_CLOSURE));
    __LAMPHEADERDATA_ret->fn = __LAMPHEADERDATA_c;
    __LAMPHEADERDATA_ret->env = __LAMPHEADERDATA_nenv;
    return __LAMPHEADERDATA_ret;
}
__LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_apply(__LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_arg0, __LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_arg1) {
    return __LAMPHEADERDATA_arg0->fn(__LAMPHEADERDATA_arg0, __LAMPHEADERDATA_arg1);
}
__LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_lookup(__LAMPHEADERDATA_ENVIRONMENT* __LAMPHEADERDATA_env, unsigned long __LAMPHEADERDATA_depth) {
    if (__LAMPHEADERDATA_depth > 0) {
        return __LAMPHEADERDATA_lookup(__LAMPHEADERDATA_env->next, __LAMPHEADERDATA_depth - 1);
    }
    else {
        return __LAMPHEADERDATA_env->value;
    }

}
__LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_self(__LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_this, __LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_arg) {
    return __LAMPHEADERDATA_this;
}
__LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_church(__LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_this, __LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_arg) {
    unsigned long int* __LAMPHEADERDATA_cptr = (unsigned long int*)__LAMPHEADERDATA_this->env;
    (*__LAMPHEADERDATA_cptr)++;
    return __LAMPHEADERDATA_this;
}
unsigned long int __LAMPHEADERDATA_decode_church(__LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_num) {
    unsigned int __LAMPHEADERDATA_init = __LAMPHEADERDATA_rptr;
    unsigned long int __LAMPHEADERDATA_c = 0;
    __LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_counter = __LAMPHEADERDATA_ccreat(__LAMPHEADERDATA_church, (__LAMPHEADERDATA_ENVIRONMENT*)&__LAMPHEADERDATA_c);
    __LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_dummy = __LAMPHEADERDATA_ccreat(__LAMPHEADERDATA_self, __LAMPHEADERDATA_NULL);
    __LAMPHEADERDATA_APPLY(__LAMPHEADERDATA_APPLY(__LAMPHEADERDATA_num, __LAMPHEADERDATA_counter), __LAMPHEADERDATA_dummy);
    __LAMPHEADERDATA_rptr = __LAMPHEADERDATA_init;
    return __LAMPHEADERDATA_c;
}
unsigned char __LAMPHEADERDATA_check_tf(__LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_cond) {
    const unsigned char __LAMPHEADERDATA_t = 1;
    const unsigned char __LAMPHEADERDATA_f = 0;
    __LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_ctrue = __LAMPHEADERDATA_ccreat(__LAMPHEADERDATA_self, (__LAMPHEADERDATA_ENVIRONMENT*)&__LAMPHEADERDATA_t);
    __LAMPHEADERDATA_CLOSURE* __LAMPHEADERDATA_cfalse = __LAMPHEADERDATA_ccreat(__LAMPHEADERDATA_self, (__LAMPHEADERDATA_ENVIRONMENT*)&__LAMPHEADERDATA_f);
    unsigned char* __LAMPHEADERDATA_result = (unsigned char*)__LAMPHEADERDATA_APPLY(__LAMPHEADERDATA_APPLY(__LAMPHEADERDATA_cond, __LAMPHEADERDATA_ctrue), __LAMPHEADERDATA_cfalse)->env;
    return *__LAMPHEADERDATA_result;
}
